# Generated by Django 6.0.1 on 2026-01-10 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_geopoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание точки'),
            preserve_default=False,
        ),
    ]
